Stage 5 directory restructure
taisei-project/taisei pull request #247
Opened 2020-08-16 19:01 UTC by StarWitch

Restructured Stage 5 directory. No co-routinization done yet. I only changed a couple of function names for clarity/consistency/workability, but for the most part it's untouched.

2020-08-25 03:00 UTC, Akaricchi requested changes
LGTM for the most part!

2020-08-28 05:29 UTC, StarWitch commented on src/stages/stage5/iku.c
> +
`induction_bullet` (now `iku_induction_bullet`) is used in both `natural_cathode` and `induction`, so I'm keeping it in `iku.c` for now.

2020-08-28 06:06 UTC, Akaricchi reviewed
Sorry, minor pedantic detail

2020-08-28 06:06 UTC, Akaricchi commented on src/stages/stage5/nonspells/midboss_survival_1.c
> +#include "survival.h"
Ditto. Just put it into `spells.h`; a separate header is overkill.

2020-08-28 06:32 UTC, StarWitch commented
Done and done. Also rebased off of master to resolve the conflicts.

2020-08-28 23:08 UTC, Akaricchi approved these changes

2020-08-28 23:09 UTC, merged